In [4]:
#Importing the Libraries
import pandas as pd

In [5]:
#data variables stored in Salary File
dataset=pd.read_csv("Salary_Data.csv")

In [6]:
dataset

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [10]:
independent=dataset[["YearsExperience"]]
dependent=dataset[["Salary"]]

In [11]:
from sklearn.model_selection import train_test_split
X_train,y_train,X_test,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [21, 9]